#!/usr/bin/env bash

export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=true
export WECHATY_PUPPET_SERVICE_ENDPOINT=127.0.0.1:8080
export WECHATY_PUPPET_SERVICE_TOKEN=xiaoyan-1bfb-4090-8c88-bigbrother666

python run.py